### OR 문제 해결
단층 퍼셉트론
|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|1|

In [6]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.20.0


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse
from tensorflow.keras.optimizers import Adam

In [7]:
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])
label = np.array([0,1,1,1])

In [ ]:
# 모델 구성
model = Sequential()
model.add(Dense(1, input_shape=(2,))) # 입력층과 출력층이 하나인 모델

In [12]:
# 컴파일
model.compile(optimizer=SGD(), loss=mse,metrics=['accuracy']) # 모델 학습
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(data, label, epochs=100) # 모델 학습

In [14]:
model.get_weights()


[array([[0.44813612],
        [0.4879628 ]], dtype=float32),
 array([0.28789777], dtype=float32)]

In [15]:
# 모델 평가
model.evaluate(data, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 1.0000 - loss: 0.0632


[0.0632440522313118, 1.0]

In [16]:
model.predict(data) # 0.5 이상이면 1, 미만이면 0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[0.28789777],
       [0.7360339 ],
       [0.77586055],
       [1.2239966 ]], dtype=float32)

단층 퍼셉트론 XOR 게이트,
,
|x1|x2|y|
|---|---|---|
|0|0|0|
|1|0|1|
|0|1|1|
|1|1|0|

In [17]:
# xor
data = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])
label = np.array([0,1,1,0])

In [19]:
# 모델 구성
model = Sequential()
# input_shape=(2,)라고 설정한 이유는 모델이 한 번에 받아들이는 데이터 한 개(샘플 하나)의 특징(Feature) 개수가 2개이기 때문입니다. 즉, 모델이 입력으로 받는 데이터는 2차원 배열 형태로, 각 샘플이 2개의 특징을 가지고 있습니다. 예를 들어, [0, 0], [1, 0], [0, 1], [1, 1]과 같은 형태의 데이터를 입력으로 받게 됩니다.
model.add(Dense(32, input_shape=(2,), activation='relu')) # 비선형성 추가: activation='relu'
model.add(Dense(1, activation='sigmoid'))

# 컴파일
model.compile(optimizer=Adam(), loss=mse, metrics=['acc'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 32)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129 (516.00 B)

 Trainable params: 129 (516.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(data, label, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 901ms/step - acc: 0.5000 - loss: 0.2618
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - acc: 0.2500 - loss: 0.2609
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - acc: 0.2500 - loss: 0.2600
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.2500 - loss: 0.2591
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.2500 - loss: 0.2583
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.2500 - loss: 0.2575
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.2500 - loss: 0.2567
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.2500 - loss: 0.2559
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - acc: 0.2500 - loss: 0.2551
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - acc: 0.2500 - loss: 0.2543
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - acc: 0.2500 - loss: 0.2536
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - acc: 0.2500 - loss: 0.2528
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/st

In [21]:
model.evaluate(data,label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 1.0000 - loss: 0.0499


[0.04985902085900307, 1.0]

In [22]:
model.predict(data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[0.36702883],
       [0.85464287],
       [0.8480752 ],
       [0.14323439]], dtype=float32)